# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63ca6c7d07ab1ef6f044d3622aeb5ca37bbb3212c0c2ea754e463a5a3ce34e03a78865c2da2b21c19e07f99f68077cdd91b92c1d4a6f2e8730bb296b59e938bb

test:
  secret_key_base: 7c76d68d7fd604fdf311122cbf174fc4b65a833285d725f3092b5a872790a6264c359cdd58f8718ea670c99a9efbb7f0bd03457df9b4f8e7b6cb71cdb3958c96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
